# Generated by Django 4.0.6 on 2022-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutinfo',
        ),
        migrations.AddField(
            model_name='facts',
            name='freelance',
            field=models.BooleanField(default=True),
        ),
    ]
