# Generated by Django 4.0.6 on 2022-07-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_projectcategory_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
    ]
