# Generated by Django 4.0.6 on 2022-07-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_project_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
    ]
